# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 686fde524ffdab79d758f5ca2d632b3fc26a17267897f6fb711ada8633fc7a1fe22b974b5cdf037233a450a39ea4b9a78e55bdc8c1c4ebf620e5666fc70cb0fd

test:
  secret_key_base: c4c47c0c513104102fc194341dd8dc2f3743378cd926439736bb827d9bed7307010fdfb0946641d9f4eba32fa36adacd4bd8f084ff74e19e8ac31cc0fccf8cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
